export enum Bank {
  IBK_BC = '기업',
  GWANGJUBANK = '광주',
  LOTTE = '롯데',
  KDBBANK = '산업',
  BC = '비씨',
  SAMSUNG = '삼성',
  SAEMAUL = '새마을',
  SHINHAN = '신한',
  SHINHYEOP = '신협',
  CITI = '씨티',
  WOORI = '우리',
  POST = '우체국',
  SAVINGBANK = '저축',
  JEONBUKBANK = '전북',
  JEJUBANK = '제주',
  KAKAOBANK = '카카오뱅크',
  KBANK = '케이뱅크',
  TOSSBANK = '토스뱅크',
  HANA = '하나',
  HYUNDAI = '현대',
  KOOKMIN = '국민',
  NONGHYEOP = '농협',
  SUHYEOP = '수협',
}
